### Wallets
POST http://localhost:8080/wallets
Content-Type: application/json

{
  "cpf": "46794905000",
  "email": "matheus@email.com",
  "name": "Matheus"
}

###
@walletId = 938d642f-4ee2-49b5-b4ae-11cabf6d1806
DELETE http://localhost:8080/wallets/{{walletId}}


###
POST http://localhost:8080/wallets/{{walletId}}/deposits
Content-Type: application/json

{
    "value": "25.12"
}
