### Wallets
POST http://localhost:8080/wallets
Content-Type: application/json

{
  "cpf": "46794905000",
  "email": "matheus@email.com",
  "name": "Matheus"
}

###
@walletId = d9242f6b-bb48-4e0a-83da-c804b4f77a01
DELETE http://localhost:8080/wallets/{{walletId}}
