### Wallets
POST http://localhost:8080/wallets
Content-Type: application/json

{
  "cpf": "55947231026",
  "email": "joao@email.com",
  "name": "joao"
}

###
@walletId = 84720a27-a6f8-4f34-ba84-cc24f611b978
DELETE http://localhost:8080/wallets/{{walletId}}


###
POST http://localhost:8080/wallets/{{walletId}}/deposits
Content-Type: application/json

{
    "value": "25.12"
}


### Transfers
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "sender": "84720a27-a6f8-4f34-ba84-cc24f611b978",
  "receiver": "0a806891-42db-4c45-bbb7-cff7c43f8e45",
  "value": "5"
}

###
GET http://localhost:8080/wallets/{{walletId}}/statement?
    page=0&
    pageSize=100

